version: "3.9"
services:
  gateway:
    depends_on:
      - keycloak
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./conf:/app/conf
    environment:
      - GATEWAY_CONFIG=conf/appsettings.keycloak.json
      - Logging__Console__FormatterName=Simple
    entrypoint: ["bash", "/app/wait-for-it.sh", "keycloak:7777", "--", "dotnet", "/app/auth-gateway.dll"]
  keycloak:
    image: "quay.io/keycloak/keycloak:17.0.1"
    command: start-dev -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled
    ports:
      - "7777:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin 
    volumes:
      - /c/Users/Manfred/Documents/artikel/keycloak-gateway/data:/opt/keycloak/data